//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter_lua_script.h"


// Declare the bitmap loading function
extern void wxC71ADInitBitmapResources();

static bool bBitmapLoaded = false;


ScriptPanelBase::ScriptPanelBase(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC71ADInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer3 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer3);
    
    m_toolbar = new wxToolBar(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTB_FLAT);
    m_toolbar->SetToolBitmapSize(wxSize(16,16));
    
    boxSizer3->Add(m_toolbar, 0, wxALL, 5);
    
    m_toolbar->AddTool(LUA_SCRIPT_ADD_SCRIPT, _("Add script"), wxXmlResource::Get()->LoadBitmap(wxT("add")), wxNullBitmap, wxITEM_NORMAL, _("Add script"), _("Add script"), NULL);
    
    m_toolbar->AddTool(LUA_SCRIPT_RUN_SCRIPT, _("Run"), wxXmlResource::Get()->LoadBitmap(wxT("play")), wxNullBitmap, wxITEM_NORMAL, _("Run script"), _("Run script"), NULL);
    
    m_toolbar->AddTool(LUA_SCRIPT_EDIT_SCRIPT, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("project-active")), wxNullBitmap, wxITEM_NORMAL, _("Edit script"), _("Edit script"), NULL);
    
    m_toolbar->AddTool(LUA_SCRIPT_DELETE_SCRIPT, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("clean")), wxNullBitmap, wxITEM_NORMAL, _("Delete script"), _("Delete script"), NULL);
    m_toolbar->Realize();
    
    wxArrayString m_listScriptsArr;
    m_listScripts = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), m_listScriptsArr, wxLB_SINGLE);
    
    boxSizer3->Add(m_listScripts, 1, wxALL|wxEXPAND, 5);
    
    SetSizeHints(200,300);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
    // Connect events
    this->Connect(LUA_SCRIPT_ADD_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::onAddScript), NULL, this);
    this->Connect(LUA_SCRIPT_RUN_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnRunScript), NULL, this);
    this->Connect(LUA_SCRIPT_EDIT_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnEditScript), NULL, this);
    this->Connect(LUA_SCRIPT_DELETE_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnDeleteScript), NULL, this);
    m_listScripts->Connect(wxEVT_COMMAND_LISTBOX_DOUBLECLICKED, wxCommandEventHandler(ScriptPanelBase::OnRunScript), NULL, this);
    
}

ScriptPanelBase::~ScriptPanelBase()
{
    this->Disconnect(LUA_SCRIPT_ADD_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::onAddScript), NULL, this);
    this->Disconnect(LUA_SCRIPT_RUN_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnRunScript), NULL, this);
    this->Disconnect(LUA_SCRIPT_EDIT_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnEditScript), NULL, this);
    this->Disconnect(LUA_SCRIPT_DELETE_SCRIPT, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(ScriptPanelBase::OnDeleteScript), NULL, this);
    m_listScripts->Disconnect(wxEVT_COMMAND_LISTBOX_DOUBLECLICKED, wxCommandEventHandler(ScriptPanelBase::OnRunScript), NULL, this);
    
}
