//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/toolbar.h>
#include <wx/listbox.h>

class ScriptPanelBase : public wxPanel
{
protected:
    enum {
        LUA_SCRIPT_ADD_SCRIPT = 1001,
        LUA_SCRIPT_DELETE_SCRIPT = 1002,
        LUA_SCRIPT_EDIT_SCRIPT = 1003,
        LUA_SCRIPT_RUN_SCRIPT = 1004,
    };
protected:
    wxToolBar* m_toolbar;
    wxListBox* m_listScripts;

protected:
    virtual void onAddScript(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRunScript(wxCommandEvent& event) { event.Skip(); }
    virtual void OnEditScript(wxCommandEvent& event) { event.Skip(); }
    virtual void OnDeleteScript(wxCommandEvent& event) { event.Skip(); }

public:
    ScriptPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(200,300), long style = wxTAB_TRAVERSAL);
    virtual ~ScriptPanelBase();
};

#endif
